spring:
  application:
    name: shop-admin
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: true
      cachePrepStmts: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 28740000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
      prepStmtCacheSize: 300
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  cache:
    type: caffeine
  servlet:
    multipart:
      max-file-size: 10MB

mybatis:
  mapper-locations: '*/**/*Mapper.xml'
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.f139.shop: DEBUG
server:
  port: 8888